// Shared option lists used across registration/admin flows.
// NOTE: When adding or updating these lists, keep objects shaped as { value, label } unless stated otherwise.

export const MALAYSIAN_STATE_OPTIONS = [
  { value: "Johor", label: "Johor" },
  { value: "Kedah", label: "Kedah" },
  { value: "Kelantan", label: "Kelantan" },
  { value: "Malacca", label: "Malacca" },
  { value: "Negeri Sembilan", label: "Negeri Sembilan" },
  { value: "Pahang", label: "Pahang" },
  { value: "Penang", label: "Penang" },
  { value: "Perak", label: "Perak" },
  { value: "Perlis", label: "Perlis" },
  { value: "Sabah", label: "Sabah" },
  { value: "Sarawak", label: "Sarawak" },
  { value: "Selangor", label: "Selangor" },
  { value: "Terengganu", label: "Terengganu" },
  { value: "Kuala Lumpur", label: "Kuala Lumpur (Federal Territory)" },
  { value: "Labuan", label: "Labuan (Federal Territory)" },
  { value: "Putrajaya", label: "Putrajaya (Federal Territory)" },
];

export const MALAYSIAN_CITY_OPTIONS = [
  "Kuala Lumpur",
  "George Town",
  "Johor Bahru",
  "Kota Kinabalu",
  "Kuching",
  "Shah Alam",
  "Petaling Jaya",
  "Ipoh",
  "Malacca City",
  "Seremban",
  "Alor Setar",
  "Kuantan",
  "Miri",
  "Sibu",
  "Sandakan",
  "Tawau",
  "Bintulu",
  "Kangar",
  "Kota Bharu",
  "Kuala Terengganu",
  "Labuan",
  "Putrajaya",
  "Seberang Perai",
  "Subang Jaya",
  "Cyberjaya",
  "Nilai",
  "Kulim",
  "Langkawi",
  "Selayang",
  "Ampang Jaya",
].map((city) => ({ value: city, label: city }));

export const EMERGENCY_RELATIONSHIP_OPTIONS = [
  "Parent",
  "Spouse",
  "Sibling",
  "Guardian",
  "Child",
  "Relative",
  "Friend",
  "Colleague",
  "Neighbour",
  "Other",
].map((label) => ({ value: label, label }));

const INSURANCE_PROVIDER_LIST = [
  "AIA Malaysia",
  "Allianz Malaysia",
  "Etiqa",
  "Great Eastern",
  "Hong Leong Assurance",
  "Manulife Malaysia",
  "Prudential BSN",
  "Sun Life Malaysia",
  "Tokio Marine Life",
  "Zurich Malaysia",
  "MCIS Insurance",
  "Generali Malaysia",
];

export const INSURANCE_PROVIDER_OPTIONS = [
  { value: "self-pay", label: "Self-pay / No insurance" },
  ...INSURANCE_PROVIDER_LIST.map((label) => ({ value: label, label })),
];

export const SURGERIES_AND_MEDICATION_HINT =
  "List past surgeries, procedures, and current or past medications with dosage and notes. Type 'None' if not applicable.";

export const RECEPTION_SHIFT_OPTIONS = ["Morning", "Afternoon", "Evening", "Night"].map((value) => ({
  value,
  label: value,
}));

// Nationality list mirrors ISO-3166 recognized countries. Keep alphabetized for usability.
export const NATIONALITY_OPTIONS = [
  { value: "Afghan", label: "Afghan" },
  { value: "Albanian", label: "Albanian" },
  { value: "Algerian", label: "Algerian" },
  { value: "American", label: "American" },
  { value: "Andorran", label: "Andorran" },
  { value: "Angolan", label: "Angolan" },
  { value: "Antiguan or Barbudan", label: "Antiguan or Barbudan" },
  { value: "Argentine", label: "Argentine" },
  { value: "Armenian", label: "Armenian" },
  { value: "Australian", label: "Australian" },
  { value: "Austrian", label: "Austrian" },
  { value: "Azerbaijani", label: "Azerbaijani" },
  { value: "Bahamian", label: "Bahamian" },
  { value: "Bahraini", label: "Bahraini" },
  { value: "Bangladeshi", label: "Bangladeshi" },
  { value: "Barbadian", label: "Barbadian" },
  { value: "Belarusian", label: "Belarusian" },
  { value: "Belgian", label: "Belgian" },
  { value: "Belizean", label: "Belizean" },
  { value: "Beninese", label: "Beninese" },
  { value: "Bhutanese", label: "Bhutanese" },
  { value: "Bolivian", label: "Bolivian" },
  { value: "Bosnian or Herzegovinian", label: "Bosnian or Herzegovinian" },
  { value: "Botswanan", label: "Botswanan" },
  { value: "Brazilian", label: "Brazilian" },
  { value: "Bruneian", label: "Bruneian" },
  { value: "Bulgarian", label: "Bulgarian" },
  { value: "Burkinabé", label: "Burkinabé" },
  { value: "Burmese", label: "Burmese" },
  { value: "Burundian", label: "Burundian" },
  { value: "Cabo Verdean", label: "Cabo Verdean" },
  { value: "Cambodian", label: "Cambodian" },
  { value: "Cameroonian", label: "Cameroonian" },
  { value: "Canadian", label: "Canadian" },
  { value: "Central African", label: "Central African" },
  { value: "Chadian", label: "Chadian" },
  { value: "Chilean", label: "Chilean" },
  { value: "Chinese", label: "Chinese" },
  { value: "Colombian", label: "Colombian" },
  { value: "Comorian", label: "Comorian" },
  { value: "Congolese (Congo-Brazzaville)", label: "Congolese (Congo-Brazzaville)" },
  { value: "Congolese (Congo-Kinshasa)", label: "Congolese (Congo-Kinshasa)" },
  { value: "Costa Rican", label: "Costa Rican" },
  { value: "Croatian", label: "Croatian" },
  { value: "Cuban", label: "Cuban" },
  { value: "Cypriot", label: "Cypriot" },
  { value: "Czech", label: "Czech" },
  { value: "Danish", label: "Danish" },
  { value: "Djiboutian", label: "Djiboutian" },
  { value: "Dominican (Dominica)", label: "Dominican (Dominica)" },
  { value: "Dominican (Dominican Republic)", label: "Dominican (Dominican Republic)" },
  { value: "Dutch", label: "Dutch" },
  { value: "East Timorese", label: "East Timorese" },
  { value: "Ecuadorean", label: "Ecuadorean" },
  { value: "Egyptian", label: "Egyptian" },
  { value: "Emirati", label: "Emirati" },
  { value: "Equatoguinean", label: "Equatoguinean" },
  { value: "Eritrean", label: "Eritrean" },
  { value: "Estonian", label: "Estonian" },
  { value: "Eswatini", label: "Eswatini" },
  { value: "Ethiopian", label: "Ethiopian" },
  { value: "Fijian", label: "Fijian" },
  { value: "Finnish", label: "Finnish" },
  { value: "French", label: "French" },
  { value: "Gabonese", label: "Gabonese" },
  { value: "Gambian", label: "Gambian" },
  { value: "Georgian", label: "Georgian" },
  { value: "German", label: "German" },
  { value: "Ghanaian", label: "Ghanaian" },
  { value: "Greek", label: "Greek" },
  { value: "Grenadian", label: "Grenadian" },
  { value: "Guatemalan", label: "Guatemalan" },
  { value: "Guinean", label: "Guinean" },
  { value: "Guinea-Bissauan", label: "Guinea-Bissauan" },
  { value: "Guyanese", label: "Guyanese" },
  { value: "Haitian", label: "Haitian" },
  { value: "Honduran", label: "Honduran" },
  { value: "Hungarian", label: "Hungarian" },
  { value: "Icelander", label: "Icelander" },
  { value: "Indian", label: "Indian" },
  { value: "Indonesian", label: "Indonesian" },
  { value: "Iranian", label: "Iranian" },
  { value: "Iraqi", label: "Iraqi" },
  { value: "Irish", label: "Irish" },
  { value: "Israeli", label: "Israeli" },
  { value: "Italian", label: "Italian" },
  { value: "Ivorian", label: "Ivorian" },
  { value: "Jamaican", label: "Jamaican" },
  { value: "Japanese", label: "Japanese" },
  { value: "Jordanian", label: "Jordanian" },
  { value: "Kazakh", label: "Kazakh" },
  { value: "Kenyan", label: "Kenyan" },
  { value: "Kiribati", label: "Kiribati" },
  { value: "Kuwaiti", label: "Kuwaiti" },
  { value: "Kyrgyz", label: "Kyrgyz" },
  { value: "Laotian", label: "Laotian" },
  { value: "Latvian", label: "Latvian" },
  { value: "Lebanese", label: "Lebanese" },
  { value: "Lesotho", label: "Lesotho" },
  { value: "Liberian", label: "Liberian" },
  { value: "Libyan", label: "Libyan" },
  { value: "Liechtensteiner", label: "Liechtensteiner" },
  { value: "Lithuanian", label: "Lithuanian" },
  { value: "Luxembourgish", label: "Luxembourgish" },
  { value: "Malagasy", label: "Malagasy" },
  { value: "Malawian", label: "Malawian" },
  { value: "Malaysian", label: "Malaysian" },
  { value: "Maldivian", label: "Maldivian" },
  { value: "Malian", label: "Malian" },
  { value: "Maltese", label: "Maltese" },
  { value: "Marshallese", label: "Marshallese" },
  { value: "Mauritanian", label: "Mauritanian" },
  { value: "Mauritian", label: "Mauritian" },
  { value: "Mexican", label: "Mexican" },
  { value: "Micronesian", label: "Micronesian" },
  { value: "Moldovan", label: "Moldovan" },
  { value: "Monégasque", label: "Monégasque" },
  { value: "Mongolian", label: "Mongolian" },
  { value: "Montenegrin", label: "Montenegrin" },
  { value: "Moroccan", label: "Moroccan" },
  { value: "Mozambican", label: "Mozambican" },
  { value: "Namibian", label: "Namibian" },
  { value: "Nauruan", label: "Nauruan" },
  { value: "Nepalese", label: "Nepalese" },
  { value: "New Zealander", label: "New Zealander" },
  { value: "Nicaraguan", label: "Nicaraguan" },
  { value: "Nigerien", label: "Nigerien" },
  { value: "Nigerian", label: "Nigerian" },
  { value: "North Korean", label: "North Korean" },
  { value: "North Macedonian", label: "North Macedonian" },
  { value: "Norwegian", label: "Norwegian" },
  { value: "Omani", label: "Omani" },
  { value: "Pakistani", label: "Pakistani" },
  { value: "Palauan", label: "Palauan" },
  { value: "Palestinian", label: "Palestinian" },
  { value: "Panamanian", label: "Panamanian" },
  { value: "Papua New Guinean", label: "Papua New Guinean" },
  { value: "Paraguayan", label: "Paraguayan" },
  { value: "Peruvian", label: "Peruvian" },
  { value: "Philippine", label: "Philippine" },
  { value: "Polish", label: "Polish" },
  { value: "Portuguese", label: "Portuguese" },
  { value: "Qatari", label: "Qatari" },
  { value: "Romanian", label: "Romanian" },
  { value: "Russian", label: "Russian" },
  { value: "Rwandan", label: "Rwandan" },
  { value: "Saint Lucian", label: "Saint Lucian" },
  { value: "Salvadoran", label: "Salvadoran" },
  { value: "Samoan", label: "Samoan" },
  { value: "San Marinese", label: "San Marinese" },
  { value: "Sao Tomean", label: "Sao Tomean" },
  { value: "Saudi Arabian", label: "Saudi Arabian" },
  { value: "Senegalese", label: "Senegalese" },
  { value: "Serbian", label: "Serbian" },
  { value: "Seychellois", label: "Seychellois" },
  { value: "Sierra Leonean", label: "Sierra Leonean" },
  { value: "Singaporean", label: "Singaporean" },
  { value: "Slovak", label: "Slovak" },
  { value: "Slovenian", label: "Slovenian" },
  { value: "Solomon Islander", label: "Solomon Islander" },
  { value: "Somali", label: "Somali" },
  { value: "South African", label: "South African" },
  { value: "South Korean", label: "South Korean" },
  { value: "South Sudanese", label: "South Sudanese" },
  { value: "Spanish", label: "Spanish" },
  { value: "Sri Lankan", label: "Sri Lankan" },
  { value: "Sudanese", label: "Sudanese" },
  { value: "Surinamese", label: "Surinamese" },
  { value: "Swedish", label: "Swedish" },
  { value: "Swiss", label: "Swiss" },
  { value: "Syrian", label: "Syrian" },
  { value: "Tajik", label: "Tajik" },
  { value: "Tanzanian", label: "Tanzanian" },
  { value: "Thai", label: "Thai" },
  { value: "Togolese", label: "Togolese" },
  { value: "Tongan", label: "Tongan" },
  { value: "Trinidadian or Tobagonian", label: "Trinidadian or Tobagonian" },
  { value: "Tunisian", label: "Tunisian" },
  { value: "Turkish", label: "Turkish" },
  { value: "Turkmen", label: "Turkmen" },
  { value: "Tuvaluan", label: "Tuvaluan" },
  { value: "Ugandan", label: "Ugandan" },
  { value: "Ukrainian", label: "Ukrainian" },
  { value: "Uruguayan", label: "Uruguayan" },
  { value: "Uzbek", label: "Uzbek" },
  { value: "Vanuatuan", label: "Vanuatuan" },
  { value: "Vatican", label: "Vatican" },
  { value: "Venezuelan", label: "Venezuelan" },
  { value: "Vietnamese", label: "Vietnamese" },
  { value: "Yemeni", label: "Yemeni" },
  { value: "Zambian", label: "Zambian" },
  { value: "Zimbabwean", label: "Zimbabwean" },
];

// Country code options render as: Flag + ISO alpha-3 + dial code.
export const COUNTRY_CALLING_CODE_OPTIONS = [
  { value: "AFG|+93", label: "🇦🇫 AFG (+93)" },
  { value: "ALB|+355", label: "🇦🇱 ALB (+355)" },
  { value: "DZA|+213", label: "🇩🇿 DZA (+213)" },
  { value: "ASM|+1684", label: "🇦🇸 ASM (+1 684)" },
  { value: "AND|+376", label: "🇦🇩 AND (+376)" },
  { value: "AGO|+244", label: "🇦🇴 AGO (+244)" },
  { value: "AIA|+1264", label: "🇦🇮 AIA (+1 264)" },
  { value: "ATA|+672", label: "🇦🇶 ATA (+672)" },
  { value: "ATG|+1268", label: "🇦🇬 ATG (+1 268)" },
  { value: "ARG|+54", label: "🇦🇷 ARG (+54)" },
  { value: "ARM|+374", label: "🇦🇲 ARM (+374)" },
  { value: "ABW|+297", label: "🇦🇼 ABW (+297)" },
  { value: "AUS|+61", label: "🇦🇺 AUS (+61)" },
  { value: "AUT|+43", label: "🇦🇹 AUT (+43)" },
  { value: "AZE|+994", label: "🇦🇿 AZE (+994)" },
  { value: "BHS|+1242", label: "🇧🇸 BHS (+1 242)" },
  { value: "BHR|+973", label: "🇧🇭 BHR (+973)" },
  { value: "BGD|+880", label: "🇧🇩 BGD (+880)" },
  { value: "BRB|+1246", label: "🇧🇧 BRB (+1 246)" },
  { value: "BLR|+375", label: "🇧🇾 BLR (+375)" },
  { value: "BEL|+32", label: "🇧🇪 BEL (+32)" },
  { value: "BLZ|+501", label: "🇧🇿 BLZ (+501)" },
  { value: "BEN|+229", label: "🇧🇯 BEN (+229)" },
  { value: "BMU|+1441", label: "🇧🇲 BMU (+1 441)" },
  { value: "BTN|+975", label: "🇧🇹 BTN (+975)" },
  { value: "BOL|+591", label: "🇧🇴 BOL (+591)" },
  { value: "BIH|+387", label: "🇧🇦 BIH (+387)" },
  { value: "BWA|+267", label: "🇧🇼 BWA (+267)" },
  { value: "BRA|+55", label: "🇧🇷 BRA (+55)" },
  { value: "IOT|+246", label: "🇮🇴 IOT (+246)" },
  { value: "VGB|+1284", label: "🇻🇬 VGB (+1 284)" },
  { value: "BRN|+673", label: "🇧🇳 BRN (+673)" },
  { value: "BGR|+359", label: "🇧🇬 BGR (+359)" },
  { value: "BFA|+226", label: "🇧🇫 BFA (+226)" },
  { value: "BDI|+257", label: "🇧🇮 BDI (+257)" },
  { value: "KHM|+855", label: "🇰🇭 KHM (+855)" },
  { value: "CMR|+237", label: "🇨🇲 CMR (+237)" },
  { value: "CAN|+1", label: "🇨🇦 CAN (+1)" },
  { value: "CPV|+238", label: "🇨🇻 CPV (+238)" },
  { value: "CYM|+1345", label: "🇰🇾 CYM (+1 345)" },
  { value: "CAF|+236", label: "🇨🇫 CAF (+236)" },
  { value: "TCD|+235", label: "🇹🇩 TCD (+235)" },
  { value: "CHL|+56", label: "🇨🇱 CHL (+56)" },
  { value: "CHN|+86", label: "🇨🇳 CHN (+86)" },
  { value: "CXR|+61", label: "🇨🇽 CXR (+61)" },
  { value: "CCK|+61", label: "🇨🇨 CCK (+61)" },
  { value: "COL|+57", label: "🇨🇴 COL (+57)" },
  { value: "COM|+269", label: "🇰🇲 COM (+269)" },
  { value: "COG|+242", label: "🇨🇬 COG (+242)" },
  { value: "COD|+243", label: "🇨🇩 COD (+243)" },
  { value: "COK|+682", label: "🇨🇰 COK (+682)" },
  { value: "CRI|+506", label: "🇨🇷 CRI (+506)" },
  { value: "CIV|+225", label: "🇨🇮 CIV (+225)" },
  { value: "HRV|+385", label: "🇭🇷 HRV (+385)" },
  { value: "CUB|+53", label: "🇨🇺 CUB (+53)" },
  { value: "CUW|+599", label: "🇨🇼 CUW (+599)" },
  { value: "CYP|+357", label: "🇨🇾 CYP (+357)" },
  { value: "CZE|+420", label: "🇨🇿 CZE (+420)" },
  { value: "DNK|+45", label: "🇩🇰 DNK (+45)" },
  { value: "DJI|+253", label: "🇩🇯 DJI (+253)" },
  { value: "DMA|+1767", label: "🇩🇲 DMA (+1 767)" },
  { value: "DOM|+1809", label: "🇩🇴 DOM (+1 809)" },
  { value: "ECU|+593", label: "🇪🇨 ECU (+593)" },
  { value: "EGY|+20", label: "🇪🇬 EGY (+20)" },
  { value: "SLV|+503", label: "🇸🇻 SLV (+503)" },
  { value: "GNQ|+240", label: "🇬🇶 GNQ (+240)" },
  { value: "ERI|+291", label: "🇪🇷 ERI (+291)" },
  { value: "EST|+372", label: "🇪🇪 EST (+372)" },
  { value: "ETH|+251", label: "🇪🇹 ETH (+251)" },
  { value: "FLK|+500", label: "🇫🇰 FLK (+500)" },
  { value: "FRO|+298", label: "🇫🇴 FRO (+298)" },
  { value: "FJI|+679", label: "🇫🇯 FJI (+679)" },
  { value: "FIN|+358", label: "🇫🇮 FIN (+358)" },
  { value: "FRA|+33", label: "🇫🇷 FRA (+33)" },
  { value: "GUF|+594", label: "🇬🇫 GUF (+594)" },
  { value: "PYF|+689", label: "🇵🇫 PYF (+689)" },
  { value: "GAB|+241", label: "🇬🇦 GAB (+241)" },
  { value: "GMB|+220", label: "🇬🇲 GMB (+220)" },
  { value: "GEO|+995", label: "🇬🇪 GEO (+995)" },
  { value: "DEU|+49", label: "🇩🇪 DEU (+49)" },
  { value: "GHA|+233", label: "🇬🇭 GHA (+233)" },
  { value: "GIB|+350", label: "🇬🇮 GIB (+350)" },
  { value: "GRC|+30", label: "🇬🇷 GRC (+30)" },
  { value: "GRL|+299", label: "🇬🇱 GRL (+299)" },
  { value: "GRD|+1473", label: "🇬🇩 GRD (+1 473)" },
  { value: "GLP|+590", label: "🇬🇵 GLP (+590)" },
  { value: "GUM|+1671", label: "🇬🇺 GUM (+1 671)" },
  { value: "GTM|+502", label: "🇬🇹 GTM (+502)" },
  { value: "GGY|+44", label: "🇬🇬 GGY (+44)" },
  { value: "GIN|+224", label: "🇬🇳 GIN (+224)" },
  { value: "GNB|+245", label: "🇬🇼 GNB (+245)" },
  { value: "GUY|+592", label: "🇬🇾 GUY (+592)" },
  { value: "HTI|+509", label: "🇭🇹 HTI (+509)" },
  { value: "HND|+504", label: "🇭🇳 HND (+504)" },
  { value: "HKG|+852", label: "🇭🇰 HKG (+852)" },
  { value: "HUN|+36", label: "🇭🇺 HUN (+36)" },
  { value: "ISL|+354", label: "🇮🇸 ISL (+354)" },
  { value: "IND|+91", label: "🇮🇳 IND (+91)" },
  { value: "IDN|+62", label: "🇮🇩 IDN (+62)" },
  { value: "IRQ|+964", label: "🇮🇶 IRQ (+964)" },
  { value: "IRN|+98", label: "🇮🇷 IRN (+98)" },
  { value: "IRL|+353", label: "🇮🇪 IRL (+353)" },
  { value: "IMN|+44", label: "🇮🇲 IMN (+44)" },
  { value: "ISR|+972", label: "🇮🇱 ISR (+972)" },
  { value: "ITA|+39", label: "🇮🇹 ITA (+39)" },
  { value: "JAM|+1876", label: "🇯🇲 JAM (+1 876)" },
  { value: "JPN|+81", label: "🇯🇵 JPN (+81)" },
  { value: "JEY|+44", label: "🇯🇪 JEY (+44)" },
  { value: "JOR|+962", label: "🇯🇴 JOR (+962)" },
  { value: "KAZ|+7", label: "🇰🇿 KAZ (+7)" },
  { value: "KEN|+254", label: "🇰🇪 KEN (+254)" },
  { value: "KIR|+686", label: "🇰🇮 KIR (+686)" },
  { value: "XKX|+383", label: "🇽🇰 XKX (+383)" },
  { value: "KWT|+965", label: "🇰🇼 KWT (+965)" },
  { value: "KGZ|+996", label: "🇰🇬 KGZ (+996)" },
  { value: "LAO|+856", label: "🇱🇦 LAO (+856)" },
  { value: "LVA|+371", label: "🇱🇻 LVA (+371)" },
  { value: "LBN|+961", label: "🇱🇧 LBN (+961)" },
  { value: "LSO|+266", label: "🇱🇸 LSO (+266)" },
  { value: "LBR|+231", label: "🇱🇷 LBR (+231)" },
  { value: "LBY|+218", label: "🇱🇾 LBY (+218)" },
  { value: "LIE|+423", label: "🇱🇮 LIE (+423)" },
  { value: "LTU|+370", label: "🇱🇹 LTU (+370)" },
  { value: "LUX|+352", label: "🇱🇺 LUX (+352)" },
  { value: "MAC|+853", label: "🇲🇴 MAC (+853)" },
  { value: "MKD|+389", label: "🇲🇰 MKD (+389)" },
  { value: "MDG|+261", label: "🇲🇬 MDG (+261)" },
  { value: "MWI|+265", label: "🇲🇼 MWI (+265)" },
  { value: "MYS|+60", label: "🇲🇾 MYS (+60)" },
  { value: "MDV|+960", label: "🇲🇻 MDV (+960)" },
  { value: "MLI|+223", label: "🇲🇱 MLI (+223)" },
  { value: "MLT|+356", label: "🇲🇹 MLT (+356)" },
  { value: "MHL|+692", label: "🇲🇭 MHL (+692)" },
  { value: "MTQ|+596", label: "🇲🇶 MTQ (+596)" },
  { value: "MRT|+222", label: "🇲🇷 MRT (+222)" },
  { value: "MUS|+230", label: "🇲🇺 MUS (+230)" },
  { value: "MYT|+262", label: "🇾🇹 MYT (+262)" },
  { value: "MEX|+52", label: "🇲🇽 MEX (+52)" },
  { value: "FSM|+691", label: "🇫🇲 FSM (+691)" },
  { value: "MDA|+373", label: "🇲🇩 MDA (+373)" },
  { value: "MCO|+377", label: "🇲🇨 MCO (+377)" },
  { value: "MNG|+976", label: "🇲🇳 MNG (+976)" },
  { value: "MNE|+382", label: "🇲🇪 MNE (+382)" },
  { value: "MSR|+1664", label: "🇲🇸 MSR (+1 664)" },
  { value: "MAR|+212", label: "🇲🇦 MAR (+212)" },
  { value: "MOZ|+258", label: "🇲🇿 MOZ (+258)" },
  { value: "MMR|+95", label: "🇲🇲 MMR (+95)" },
  { value: "NAM|+264", label: "🇳🇦 NAM (+264)" },
  { value: "NRU|+674", label: "🇳🇷 NRU (+674)" },
  { value: "NPL|+977", label: "🇳🇵 NPL (+977)" },
  { value: "NLD|+31", label: "🇳🇱 NLD (+31)" },
  { value: "BES|+599", label: "🇳🇱 BES (+599)" },
  { value: "NCL|+687", label: "🇳🇨 NCL (+687)" },
  { value: "NZL|+64", label: "🇳🇿 NZL (+64)" },
  { value: "NIC|+505", label: "🇳🇮 NIC (+505)" },
  { value: "NER|+227", label: "🇳🇪 NER (+227)" },
  { value: "NGA|+234", label: "🇳🇬 NGA (+234)" },
  { value: "NIU|+683", label: "🇳🇺 NIU (+683)" },
  { value: "NFK|+672", label: "🇳🇫 NFK (+672)" },
  { value: "PRK|+850", label: "🇰🇵 PRK (+850)" },
  { value: "MNP|+1670", label: "🇲🇵 MNP (+1 670)" },
  { value: "NOR|+47", label: "🇳🇴 NOR (+47)" },
  { value: "OMN|+968", label: "🇴🇲 OMN (+968)" },
  { value: "PAK|+92", label: "🇵🇰 PAK (+92)" },
  { value: "PLW|+680", label: "🇵🇼 PLW (+680)" },
  { value: "PAN|+507", label: "🇵🇦 PAN (+507)" },
  { value: "PNG|+675", label: "🇵🇬 PNG (+675)" },
  { value: "PRY|+595", label: "🇵🇾 PRY (+595)" },
  { value: "PER|+51", label: "🇵🇪 PER (+51)" },
  { value: "PHL|+63", label: "🇵🇭 PHL (+63)" },
  { value: "POL|+48", label: "🇵🇱 POL (+48)" },
  { value: "PRT|+351", label: "🇵🇹 PRT (+351)" },
  { value: "PRI|+1787", label: "🇵🇷 PRI (+1 787)" },
  { value: "QAT|+974", label: "🇶🇦 QAT (+974)" },
  { value: "REU|+262", label: "🇷🇪 REU (+262)" },
  { value: "ROU|+40", label: "🇷🇴 ROU (+40)" },
  { value: "RUS|+7", label: "🇷🇺 RUS (+7)" },
  { value: "RWA|+250", label: "🇷🇼 RWA (+250)" },
  { value: "SHN|+290", label: "🇸🇭 SHN (+290)" },
  { value: "KNA|+1869", label: "🇰🇳 KNA (+1 869)" },
  { value: "LCA|+1758", label: "🇱🇨 LCA (+1 758)" },
  { value: "MAF|+590", label: "🇲🇫 MAF (+590)" },
  { value: "SPM|+508", label: "🇵🇲 SPM (+508)" },
  { value: "VCT|+1784", label: "🇻🇨 VCT (+1 784)" },
  { value: "WSM|+685", label: "🇼🇸 WSM (+685)" },
  { value: "SMR|+378", label: "🇸🇲 SMR (+378)" },
  { value: "STP|+239", label: "🇸🇹 STP (+239)" },
  { value: "SAU|+966", label: "🇸🇦 SAU (+966)" },
  { value: "SEN|+221", label: "🇸🇳 SEN (+221)" },
  { value: "SRB|+381", label: "🇷🇸 SRB (+381)" },
  { value: "SYC|+248", label: "🇸🇨 SYC (+248)" },
  { value: "SLE|+232", label: "🇸🇱 SLE (+232)" },
  { value: "SGP|+65", label: "🇸🇬 SGP (+65)" },
  { value: "SXM|+1721", label: "🇸🇽 SXM (+1 721)" },
  { value: "SVK|+421", label: "🇸🇰 SVK (+421)" },
  { value: "SVN|+386", label: "🇸🇮 SVN (+386)" },
  { value: "SLB|+677", label: "🇸🇧 SLB (+677)" },
  { value: "SOM|+252", label: "🇸🇴 SOM (+252)" },
  { value: "ZAF|+27", label: "🇿🇦 ZAF (+27)" },
  { value: "KOR|+82", label: "🇰🇷 KOR (+82)" },
  { value: "SSD|+211", label: "🇸🇸 SSD (+211)" },
  { value: "ESP|+34", label: "🇪🇸 ESP (+34)" },
  { value: "LKA|+94", label: "🇱🇰 LKA (+94)" },
  { value: "SDN|+249", label: "🇸🇩 SDN (+249)" },
  { value: "SUR|+597", label: "🇸🇷 SUR (+597)" },
  { value: "SJM|+47", label: "🇸🇯 SJM (+47)" },
  { value: "SWZ|+268", label: "🇸🇿 SWZ (+268)" },
  { value: "SWE|+46", label: "🇸🇪 SWE (+46)" },
  { value: "CHE|+41", label: "🇨🇭 CHE (+41)" },
  { value: "SYR|+963", label: "🇸🇾 SYR (+963)" },
  { value: "TWN|+886", label: "🇹🇼 TWN (+886)" },
  { value: "TJK|+992", label: "🇹🇯 TJK (+992)" },
  { value: "TZA|+255", label: "🇹🇿 TZA (+255)" },
  { value: "THA|+66", label: "🇹🇭 THA (+66)" },
  { value: "TLS|+670", label: "🇹🇱 TLS (+670)" },
  { value: "TGO|+228", label: "🇹🇬 TGO (+228)" },
  { value: "TKL|+690", label: "🇹🇰 TKL (+690)" },
  { value: "TON|+676", label: "🇹🇴 TON (+676)" },
  { value: "TTO|+1868", label: "🇹🇹 TTO (+1 868)" },
  { value: "TUN|+216", label: "🇹🇳 TUN (+216)" },
  { value: "TUR|+90", label: "🇹🇷 TUR (+90)" },
  { value: "TKM|+993", label: "🇹🇲 TKM (+993)" },
  { value: "TCA|+1649", label: "🇹🇨 TCA (+1 649)" },
  { value: "TUV|+688", label: "🇹🇻 TUV (+688)" },
  { value: "VIR|+1340", label: "🇻🇮 VIR (+1 340)" },
  { value: "UGA|+256", label: "🇺🇬 UGA (+256)" },
  { value: "UKR|+380", label: "🇺🇦 UKR (+380)" },
  { value: "ARE|+971", label: "🇦🇪 ARE (+971)" },
  { value: "GBR|+44", label: "🇬🇧 GBR (+44)" },
  { value: "USA|+1", label: "🇺🇸 USA (+1)" },
  { value: "URY|+598", label: "🇺🇾 URY (+598)" },
  { value: "UZB|+998", label: "🇺🇿 UZB (+998)" },
  { value: "VUT|+678", label: "🇻🇺 VUT (+678)" },
  { value: "VAT|+39", label: "🇻🇦 VAT (+39)" },
  { value: "VEN|+58", label: "🇻🇪 VEN (+58)" },
  { value: "VNM|+84", label: "🇻🇳 VNM (+84)" },
  { value: "WLF|+681", label: "🇼🇫 WLF (+681)" },
  { value: "YEM|+967", label: "🇾🇪 YEM (+967)" },
  { value: "ZMB|+260", label: "🇿🇲 ZMB (+260)" },
  { value: "ZWE|+263", label: "🇿🇼 ZWE (+263)" },
];
